### ISSUE TITLE
Grung source

### ISSUE THREAD

**Issue by stribor14** [astranauta/astranauta.github.io#475]
Please fill out as much of this template as possible/is applicable.

Is this a bug or a feature request:
Wrong info / Feature request

Issue:
Source for Grung is noted as OGA (One Grung Above) but the problem is that the published source doesn't have Grung variants and some of the traits differ. Could you add the official Grung build and specify the source material from where those variants came?

I think variants on the page are homebrewed from information available in VGtM and the OGA.

Page(s) affected: Races

Reproduction steps: -

Additional information: - 

Browser (Chromium, Firefox, Edge, etc): -

Platform (Windows, iOS, Android, etc): -

**Comment by MrLabRat** [comment]
Fixed!

**Comment by stribor14** [comment]
Sorry for bumping this again. It isn't fixed yet, but PR #484 did implement said fix.
